name: conda-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - ipyparallel==9.0.0
  - loguru=0.7.2
  - lxml=5.3.0
  - matplotlib=3.9.3
  - numpy=1.26.4
  - pandas=2.2.2
  - pyarrow=18.0.0
  - pygmo=2.19.7
  - jupyter>=1.1.1
  - pytables=3.10.2
  - h5py=3.12.1
  - pip
  - pip:
      - phd-visualizations @ git+https://github.com/juan11iguel/phd_visualizations@main
      - pydantic==2.9.2
      - -e /workspaces/devcontainer_template/modeling # Should be an actual python package
      - -e /workspaces/devcontainer_template/simulation # # Should be an actual python package
