[project]
name = "decvontainer_template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "juan11iguel", email = "juan11iguel@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.0",
    "pandas>=2.2.3",
    "solhycool-modeling",
]

[project.scripts]
solhycool-optimization = "solhycool_optimization:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
solhycool-modeling = { path = "../modeling", editable = true }

[dependency-groups]
dev = [
    "jupyter>=1.1.1",
]
